language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run lint
  - npm run build

after_success:
  - npm run package

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "dist/cpm-map-*.tgz"
  api_key: $GITHUB_TOKEN
  on:
    branch: master